### PR TITLE
Fix #33 Add Appveyor CI

### LINKED ISSUE #33: Add Appveyor CI
https://www.appveyor.com/ is a CI much like Travis CI, with one substantial difference that it runs on Windows. Needles to say, we need this to see that every commit and PR is passing on both Linux and Windows. I have set it up several times in the past, hence I can do that.

### PR DESCRIPTION
**Pull request by ppalaga**
The appveyor CI works against my fork: https://ci.appveyor.com/project/ppalaga/ec4j/build/1.0.6#L1910

@angelozerr either enable it yourself for your master ec4j repo or delegate the permission to me.

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @ppalaga !

**Comment by angelozerr** [comment]
> @angelozerr either enable it yourself for your master ec4j repo or delegate the permission to me.

Which permission do you need? Github permission?

**Comment by angelozerr** [comment]
@ppalaga I have added as collaborator for ec4j. Tell me if it's that that you wish to have.

**Comment by ppalaga** [comment]
> I have added as collaborator for ec4j. Tell me if it's that that you wish to have.

No, that's unfortunately not what I'd need. I could push with that one, but I still cannot view/edit the settings of the repo, esp. the hooks. You can remove me from collaborators again.

As I tried to explain in an e-mail, this kind of thing can only be delegated when the repo is owned by an organization. GitHub organizations allow much finer grained permissions management than personal repos. 

So, my position is still that you can either 

(a) create a new `ec4j` GitHub org (see e.g. https://help.github.com/articles/creating-a-new-organization-from-scratch/ ), transfer the `ec4j` repo to that org and grant me the admin permission for the `ec4j` repo.

or 

(b) you can setup the Appveyor hook yourself. It is not hard, just google for "Appveyor GitHub".

**Comment by angelozerr** [comment]
Sorry @ppalaga I have read too quickly your great explanation -( Thanks again to re-explain me. As we have discussed together, I would like to see how it could work with ec4e if I will move ec4e to eclipse

**Pull request merged**
