### PR TITLE
 Fix #30 and #31 

### LINKED ISSUE #30: Add missing @author tags
There is a lot of classes not having an `@author` tag at all. I'd attribute them to you @angelozerr except for classes that state that they were copied from somewhere else. I have fix ready that I can submit after #29 is merged.

### PR DESCRIPTION
**Pull request by ppalaga**
@angelozerr so this are the changes we need, to be able to refactor `ec4e` too.

### CODE REVIEW

**Comment by ppalaga** [comment]
Also note that the core tests work on Travis now: https://travis-ci.org/ppalaga/ec4j/jobs/293021759#L2331

**Comment by angelozerr** [comment]
Thanks @ppalaga !

**Comment by angelozerr** [comment]
It's a very cool news! Do you know why my travis has not the same score than yours https://travis-ci.org/angelozerr/ec4j/jobs/293023926#L2371 ?

**Comment by ppalaga** [comment]
> Do you know why my travis has not the same score than yours https://travis-ci.org/angelozerr/ec4j/jobs/293023926#L2371 ?

Strange. No idea. Locally, I still see only one test fail with revision 59502a0264d8fcd150a03d454dadfc12ee32bf1c

**Pull request merged**
