### PR TITLE
 Fix #42 EditorConfig, Section, Option with location

### LINKED ISSUE #42: EditorConfig, Section, Option with location
Today completion, validation,hover, parse each time the editorconfig content. It should be better to use an AST EditorConfig instance to do that (like JDT does with ICompilationUnit).

In other words the IDE maintains an instance of EditorConfig and use it for IDE services like completion, validation, hover, codelens, folding, etc

To do that the EditorConfig, Section, Option class must have start/end location. But @ppalaga I know that you don't need this location info. Here my proposition:

 * add withLocation(boolean) to the parser to store or not the location
 * add Section#start, Section#end, etc which are null when  withLocation(false) or create SectionAndLoc which extends Section.

@ppalaga what do you think about that?

### PR DESCRIPTION
**Pull request by ppalaga**
@angelozerr this is not perfectly polished yet, just an idea how I think it could work. 

Mainly, the test is unfinished: https://github.com/angelozerr/ec4j/compare/master...ppalaga:i42?expand=1#diff-582920529e0203ec7c81702f7a6e47d3R44 In that test stub, you can see how the Location info can be accessed. 

Is the idea acceptable?

Using the adaptable pattern that you may know from Eclipse is IMO the best way to implement this. Other options like subclassing the model would lead to tons of generics. I tried it but I did not like the result. With the present solution, the default model can stay free of any non-core model info and at the same time users are free to "hang" any additional info on the model, such as model element locations.

### CODE REVIEW

**Comment by ppalaga** [comment]
Actually, it would be nice if you could tell me what the correct spans for the test file are https://github.com/angelozerr/ec4j/compare/master...ppalaga:i42?expand=1#diff-582920529e0203ec7c81702f7a6e47d3R44 I find it quite possible that the parser does not send the events quite precisely and I do not know what are the correct locations (that you know I hope).

**Comment by angelozerr** [comment]
> Other options like subclassing the model would lead to tons of generics. I tried it but I did not like the result. With the present solution, the default model can stay free of any non-core model info and at the same time users are free to "hang" any additional info on the model, such as model element locations.

My first though about API was to have that:

```
Section section = ....
Location start = section.getStart()
Location end = section.getEnd()
Location end = section.getEndEnclosed()
```

Your proposition is:

```
Section section = ....
SectionSpan span = section.getAdapter(SectionSpan.class)
Location start = span.getStart()
Location end = span.getEnd()
Location end = span.getEndEnclosed()
```

I found it's a little more verbose but very acceptable if you think it's better to have a clean Section class.

> Actually, it would be nice if you could tell me what the correct spans for the test file are https://github.com/angelozerr/ec4j/compare/master...ppalaga:i42?expand=1#diff-582920529e0203ec7c81702f7a6e47d3R44

I will try to do that ASAP, but I'm a little busy for the moment with CodeLens contribution for Photon. I would lik eto implement folding and outline in ec4e and it will be more easy to detect problem. Do you want I do that?

**Comment by ppalaga** [comment]
> it's a little more verbose but very acceptable

Nice to hear that, thanks.

What is `span.getEndEnclosed()` supposed to return?

**Comment by ppalaga** [comment]
> I will try to do that ASAP, but I'm a little busy for the moment with CodeLens contribution for Photon. I would lik eto implement folding and outline in ec4e and it will be more easy to detect problem. Do you want I do that?

My position is that I'd very much like to have at least one unit test for the location aware model. I am not able to write the test, because I do not know where exactly the starts and ends should be. Therefore, I prefer you to finish the test and optionally, you also fix the parser, if it is doing something wrong. I do not care much when you do that. 

If you prefer to do that later, I am OK with merging this PR without the test (once I declare the other stuff in this PR finished). In such a case we can create a new issue to track finishing the test.

WDYT?

**Comment by ppalaga** [comment]
6d5607a is good enough to get a final review and eventually get merged. In such a case, a new issue to finish the test needs to be created.

**Comment by angelozerr** [comment]
> My position is that I'd very much like to have at least one unit test for the location aware model. I am not able to write the test, because I do not know where exactly the starts and ends should be. Therefore, I prefer you to finish the test and optionally, you also fix the parser, if it is doing something wrong. I do not care much when you do that.

Ok I understand.

The basic idea is to have start/end and enclosed location for Section to Validation, CodeLens and Folding. Takes a simple case:

```
[*]
a = b
c = d
e = f

[a.js]
```

For [*], I need 3 location:

 * the location of '[' before `*` to support Codelens and display before this location a text like `x files match`. I mean start of Section.
 * the location of ']' after `*` to support validation of the pattern to highlight error when pattern is not valid. I mean end of Section. But perhaps this location is wrong and it's more a location for pattern and not for section?
 * the location of `f` to support folding for the section. I would like to fold/unfold section. I mean enclosed location.

Is it more clear?

> If you prefer to do that later, I am OK with merging this PR without the test (once I declare the other stuff in this PR finished). In such a case we can create a new issue to track finishing the test.

Ok let's go, we create a new issue for that. If you have time and you understand my need for section location, it's very cool otherwise I will do it.

**Comment by angelozerr** [comment]
Thanks @ppalaga !

**Comment by angelozerr** [comment]
> If you prefer to do that later, I am OK with merging this PR without the test (once I declare the other stuff in this PR finished). In such a case we can create a new issue to track finishing the test.

Please see https://github.com/angelozerr/ec4j/issues/55

**Pull request merged**
