### PR TITLE
Fix #50 Use fr.opensagres.ec4j as groupId

### LINKED ISSUE #50: Use fr.opensagres.ec4j as groupId
Maven groups should gather artifacts that have a common release cycle. There is a lot of other stuff present under `fr.opensagres` on Maven Central already [1] that has nothing to do with ec4j. Therefore, we want to use `groupId` unique to the artifacts produced by this project, such as `fr.opensagres.ec4j`.

[1] http://central.maven.org/maven2/fr/opensagres/

### PR DESCRIPTION
**Pull request by ppalaga**
@angelozerr this is all of what I propose in #50, but I am still ready to discuss the individual parts.

### CODE REVIEW

**Comment by angelozerr** [comment]
@ppalaga I would like to avoid renaming package for the moment by waiting discussion that we have with @mickaelistria if ec4j will mov eor not to eclipse.org

Hope you will understand.

**Comment by ppalaga** [comment]
I have no problem with waiting for the result of the "ec4j home" discussion. I'd like to re-state that (1) we should use the same namespace everywhere (groupId, artifactId, Bundle-SymbolicName and Java packages) (2) we should use a namespace we are allowed to use.

Unless this project goes to ESF within a few months, the present PR should be merged. Otherwise, a5a9687e877ec0aa104853fb59b0e2edf984fcf0 should be reverted. Both options are consistent, but the present state is not.

BTW, the first commit f7061c4 fixes a checkstyle problem present in master. Could you please cherry-pick it to master branch?

**Comment by angelozerr** [comment]
Ok @ppalaga I think for the moment the best mean is to use fr.opensagres. Thanks for your PR!

Waiting for ec4e PR to accept your PR.

**Comment by ppalaga** [comment]
Let's wait a bit till we are 100% sure where ec4j goes to ESF or not

**Comment by ppalaga** [comment]
Out of date.

**Pull request closed without merging**
