### PR TITLE
 Fix #28 Split ec4j into core and services

### LINKED ISSUE #28: Split ec4j into core and services
I propose to move the `org.eclipse.ec4j.completion` and `org.eclipse.ec4j.validation` packages (plus a few other related classes) back to ec4e. 

Motivation: The current completion and validation functionality is designed in the way usual for Eclipse plugins (although it tries to be generic). I am sure it will not be needed in the maven plugin I work on and I quite doubt that any other IDE's plugin would benefit from it. Keeping it here in ec4j would cause an unnecessary maintenance overhead and once the code is moved to ec4e, it could be simplified substantially through making it less generic and more tightly bound to Eclipse APIs. 

What is your opinion, @angelozerr ?

### PR DESCRIPTION
**Pull request by ppalaga**

### CODE REVIEW

**Comment by ppalaga** [comment]
9e1f1c6 split the current project into core and services modules

**Comment by angelozerr** [comment]
@ppalaga have you a PR for ec4e which uses the new packages?

**Comment by ppalaga** [comment]
> have you a PR for ec4e which uses the new packages?

I have this branch of ec4e https://github.com/ppalaga/ec4e/tree/171025-ec4j-split that consumes revision 9f9413c from my ec4j branch https://github.com/ppalaga/ec4j/commits/i31 . The 171025-ec4j-split compiles, but I have not run the code in any way (no time and don't know how).

**Comment by angelozerr** [comment]
Thanks a lot @ppalaga for your great PR!

**Comment by angelozerr** [comment]
Could you create a PR for ec4e please.

**Comment by ppalaga** [comment]
> Could you create a PR for ec4e please.

Yes, but first I have to submit a PR here in `ec4j` for the rest of the changes I have in my https://github.com/ppalaga/ec4j/commits/i31 branch. Let me do that now.

**Comment by angelozerr** [comment]
> Let me do that now.

Thanks @ppalaga!

**Comment by ppalaga** [comment]
I have submitted the PR to `ec4j` https://github.com/angelozerr/ec4e/pull/20

**Pull request merged**
